
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1356/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.15.133.1-microsoft-standard-WSL2 - x86_64
...
